version: 2.1
orbs:
  helm: entur/helm@0.0.13
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/build.sh
  deploy-helm:
    docker:
      - image: entur/cci-toolbox:2.1 # This executor comes with a lof of pre-installed features; including gcloud.
    steps:
    - helm/install-helm-chart:
        chart: ./kubernetes/ink-network
        namespace: ink
        release-name: ink
        app-version: 0.1.13
        version: 0.1.13
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: ink-remix
          filters:
            branches:
              only: 
              - develop
              - staging
              - master
      - deploy-helm:
          context: ink-remix
          # filters:
          #   branches:
          #     only: 
          #     - develop
          #     - staging
          #     - master
