version: 2.1
orbs:
  helm: circleci/helm@0.2.3
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker
      - run: ./scripts/build.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: ink-remix
          filters:
            branches:
              only: 
              - develop
              - staging
              - master
